server:
  port: 33400

general:
  kafka-topic: test-topic

spring:
  kafka:
    consumer:
      group-id: midas-core-group
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        '[spring.json.trusted.packages]': "com.jpmc.midascore.foundation"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer